SIDE_LEN_ACT = 15
SIDE_LEN = SIDE_LEN_ACT + 2  # Including the walls.

EMPTY = 1 << 0
BLACK = 1 << 1
WHITE = 1 << 2
WALL = 1 << 3

# NOTE: Generic Patterns are specified from BLACK's POV.
OWN = BLACK
ENEMY = WHITE
STONE = OWN | ENEMY
ANY = EMPTY | STONE | WALL
NOT_EMPTY = ANY ^ EMPTY
NOT_WALL = ANY ^ WALL
NOT_STONE = ANY ^ STONE
NOT_OWN = ANY ^ OWN

NUM_DIRECTIONS = 8
